/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#060e20",
        "secondary": "#5de6ff",
        "tertiary-fixed-dim": "#ddb8ff",
        "error": "#ffb4ab",
        "inverse-primary": "#6d3bd7",
        "on-tertiary-fixed-variant": "#62259b",
        "on-surface-variant": "#cbc3d7",
        "surface-tint": "#d0bcff",
        "surface-container-highest": "#2d3449",
        "primary": "#d0bcff",
        "on-error-container": "#ffdad6",
        "surface": "#0b1326",
        "outline": "#958ea0",
        "surface-bright": "#31394d",
        "on-secondary-fixed-variant": "#004e5a",
        "surface-dim": "#0b1326",
        "surface-container-low": "#131b2e",
        "on-secondary-fixed": "#001f25",
        "inverse-surface": "#dae2fd",
        "on-primary-container": "#340080",
        "secondary-fixed-dim": "#2fd9f4",
        "tertiary-container": "#b175ec",
        "on-primary-fixed-variant": "#5516be",
        "on-secondary": "#00363e",
        "on-secondary-container": "#00515d",
        "on-surface": "#dae2fd",
        "on-tertiary-container": "#400071",
        "tertiary": "#ddb8ff",
        "surface-variant": "#2d3449",
        "secondary-container": "#00cbe6",
        "on-tertiary": "#490081",
        "outline-variant": "#494454",
        "on-primary": "#3c0091",
        "error-container": "#93000a",
        "primary-fixed-dim": "#d0bcff",
        "inverse-on-surface": "#283044",
        "primary-fixed": "#e9ddff",
        "primary-container": "#a078ff",
        "tertiary-fixed": "#f0dbff",
        "surface-container-high": "#222a3d",
        "on-background": "#dae2fd",
        "on-primary-fixed": "#23005c",
        "on-error": "#690005",
        "background": "#0b1326",
        "on-tertiary-fixed": "#2c0051",
        "surface-container": "#171f33",
        "secondary-fixed": "#a2eeff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "0.25rem",
        "sm": "0.5rem",
        "base": "8px",
        "md": "1rem",
        "lg": "2rem",
        "xl": "4rem",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-max": "1280px"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "button-text": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-md": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "button-text": ["16px", { lineHeight: "24px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}